/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardGenericContainer: typeof import('./src/components/CardGenericContainer.vue')['default']
    CardTree: typeof import('./src/components/CardTree.vue')['default']
    CardTypography: typeof import('./src/components/CardTypography.vue')['default']
    ComponentFilter: typeof import('./src/components/ComponentFilter.vue')['default']
    GRMEquipmentJobDetails: typeof import('./src/components/GRMEquipmentJobDetails.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PropertyControl: typeof import('./src/components/PropertyControl.vue')['default']
    SampleAppSlideOut: typeof import('./src/components/SampleAppSlideOut.vue')['default']
  }
}
